version: '3'

services:
  laravel:
    container_name: laravel
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - 8007:8007
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: materias
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

